### ISSUE TITLE
API key error

### ISSUE THREAD

**Issue by hurzl** [SecUSo/privacy-friendly-weather#106]
I registered at openweathermap.org and got an API key which I entered.
Trying to update weather I get an error now.

... Now 2 mins later I get no more error but the time stamp stays the same (at 1 1/2 h ago). ..

**Comment by sleep-yearning** [comment]
Hello @hurzl 
Is the time stamp updating on leaving & reentering the app? Because that's another issue currently. 
Furthermore, does the update work with your personal API key?

**Comment by hurzl** [comment]
> Is the time stamp updating on leaving & reentering the app? Because that's another issue currently.

yes
> Furthermore, does the update work with your personal API key?

how do I know?

**Comment by sleep-yearning** [comment]
Thanks for answering, 
I meant if you get updates now with your own key. 
Because you wrote you stopped getting errors but not if the data get's updated.

**Comment by hurzl** [comment]
I get updates but don't know how often

**Comment by hurzl** [comment]
The timestamp only changes in one hour steps

**Comment by woheller69** [comment]
Hi sleep-yearning, I also think there might be an issue with the api key.
I just implemented a new activity for an animated rain radar using OpenStreetMap and RainViewer API, which you can checkout on my work-branch2.
In order to get latitude and longitude from cityid I am reading the api key via  API_KEY = OwmApiData.getAPI_KEY();
and pass it to my rainviewer.html page which retrieves latitude longitude from Openweather. 
For debugging reasons I am showing cityid and api key on the page (see picture).

I see the following behaviour:
After updating the app my own api key is shown in settings.
When I open my rainviewer activity it shows the default api key 3fb2....
When I now go back to settings, open the api key setting and just press ok,
it will be using my own api-key. But when I kill the app with a task manager or reboot the
phone it again uses the default api key even though  it shows my own key in settings.

![Screenshot_20200830-070432](https://user-images.githubusercontent.com/68678880/91651748-a3a65a80-ea90-11ea-890e-d1ecbd262992.png)
![Screenshot_20200830-070438](https://user-images.githubusercontent.com/68678880/91651750-a608b480-ea90-11ea-860e-709adc454a43.png)

**Comment by sleep-yearning** [comment]
Thanks for reporting, this is troubling

**Comment by woheller69** [comment]
I think I found a way to solve this. Please have a look at commit 39a415e7d655c17fe6b5aecc64fa3ac30fd5b7cc in my branch newmaster.

I actually removed the OwmApiData class. The key is now read via AppPreferencesManager and the BASE_URL comes from BuildConfig. I now see the right key also after a reboot. Maybe there is a better solution, I am a Java beginner...
