### ISSUE TITLE
Widget for weather display for certain city

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-weather#18]

**Comment by logos88** [comment]
Hi! Thanks for this great app. Its nice to have a weather aplication which respects the privacy : )

For me a widget that shows the current and next days weather is the very important since it leaves me to know with only a look how is the weather and how is going to evolve. 

One widget I like is the one from eltiempo.es app. I leave an image with two different widgets as example in case it helps for ideas:

![eltiempo](https://cloud.githubusercontent.com/assets/4170088/20339530/257d65a4-abdd-11e6-95d5-0c0bf34f0308.png)

The upper image its a 4x2 widget. It has info about the current day in the firs row, with the name and number of the day, the maximum and minimum temperatures, the wind direction and velocity, the sunrise and twilight hour, the percentage of clouds and precipitations. In the second row, on the other hand, you can easily see how the weather is going to evolve the next three days with their minimum and maximum temperatures, the wind and the precipitations.

The second one down its a 4x1 widget instead. Its a simpler possibility that shows the maximum and minimum temperatures of the current day and the next two too.

**Comment by jobbb** [comment]
When you plan to add widgets?

**Comment by Yonjuni** [comment]
@jobbb I can not say a specific date, yet.

**Comment by Yonjuni** [comment]
The redesign will include a widget showing temperature, weather, humidity and name of default location or desired location.

**Comment by jobbb** [comment]
with forecast? How many days? Are the number of days choosable as an option?

**Comment by Yonjuni** [comment]
The app will show the forecast for 5 days inside. 
One widget will have today's weather (weather type, temperature, humidity and location)
It could be doable to add another one having the same data for five days.

**Comment by jobbb** [comment]
a widget for up to five days would be great!!

**Comment by Yonjuni** [comment]
Closed #18

**Comment by logos88** [comment]
Does this mean it won't be implemented?

**Comment by Yonjuni** [comment]
It is already implemented and will be published in version 2.0

**Comment by logos88** [comment]
Great! Thanks! :+1:

**Comment by fliegentoeter** [comment]
Are there any news about a widget option?
Really like these apps but a weather app without a widget is pretty useless.

**Comment by Yonjuni** [comment]
@fliegentoeter We're currently doing the final testing and bug fixing of the new update. This will have different widget types.

**Comment by fliegentoeter** [comment]
That's great. Is there any timeframe when it will be released? Weeks, month, years?
There is really no good weather app available in fdroid. This one is the only one looking good but has no widget yet -.-

**Comment by Yonjuni** [comment]
Dear all, we have just made the update which includes widgets.
