### ISSUE TITLE
weather app is not starting (calyxos)

### ISSUE THREAD

**Issue by madtibo** [SecUSo/privacy-friendly-weather#188]
On pixel4a with calyxos 3.3.0 and Android 12.

The app would not start.

Please find the Android report : https://tribu-ml.fr/nextcloud/s/r7M9f5Q2wq9bDbx

**Comment by sleep-yearning** [comment]
Thank you for the report. 
It looks like the app is crashing because some of the weather data is not as expected (specifically the rain forecast for the next hour) for a city.
Deleting App data and re-filling should work until you add the problematic city. Maybe the weather data will be back to normal at some point as well.

Nevertheless, this could be prevented by adding a catch in RecycleList>CityWeatherAdapter:~838 to check if the data (rain60min) has sufficient elements for the current index.

**Comment by madtibo** [comment]
Thanks a lot for the information. It works like a charm after the reset.

**Comment by linesquarecube** [comment]
Hi, I have the same phone / OS combination and the same issue this morning. Thanks for the hint @sleep-yearning, reseting also fixed the app for me :+1:

**Comment by madtibo** [comment]
Since there is a workaround, I close the issue.
