### ISSUE TITLE
Can't find my city, too many duplicates

### ISSUE THREAD

**Issue by georgedorn** [SecUSo/privacy-friendly-weather#72]
I live in a city with a fairly common name, so when I type it in a bunch of other cities with the same name pop up, but not mine.  Mine is the largest city with this name, but it doesn't show up in the list.  I can't filter the list by State, either, which would solve this problem.

Perhaps a zip code entry mechanism?

**Comment by petermayer** [comment]
Thanks for the suggestion, we will keep it in mind for future versions of the app.

**Comment by CyrusCT** [comment]
I am also impacted: Unable to add San Francisco, California, United States because of some other country's San Francisco having 8+ instances.  Having more results listed, a zip code filter" or country filter would help.  Being able to add locations from the radius search would also be a viable workaround.

**Comment by siccovansas** [comment]
Maybe related. When I search for 'Amsterdam' I only see the small town called Amsterdam in the US, while I can't see the Amsterdam from the Netherlands.

**Comment by sleep-yearning** [comment]
For now, this should be fixed by 9d94e38ef1495b90ea86a8071089e2e19e2147f6. 
There is a more elegant solutions in the plans, but the last release should have solved that problem for now.
