### ISSUE TITLE
Your device is not connected to the internet

### ISSUE THREAD

**Issue by justdiver** [SecUSo/privacy-friendly-weather#74]
I just installed for the first time.  I cannot get the app working, though.  When I launch the app I keep getting a messaged that "Your device is not connected to the internet."  Nothing I do seems to fix this.

**Comment by v-i-r-u-s** [comment]
Same problem with me. 

The app sends an ICMP request to api.openweathermap.org which is of course blocked by my firewall. 

Too bad - wanted to use the app as a replacement for the spyware-contaminated weather apps you otherwise get on the Fire TV Stick (which would also work fine), but ICMP to WAN - never .

**Comment by esrat** [comment]
Hi,
I have the same problem!

The app is using some "own" code within UpdateDataService.isOnline(), running some seperate process for the ping-command. That's the reason for not seeing any network activity of the app.

These few lines only have to be replaced by a common call to InetAddress.isReachable(...)!
(Then the app itself would make the request and everybody could configure their firewalls accordingly.)

I think everybody could make this very little change (3 lines?) - despite myself since I have no development environment for Android. --- So, can you please fix (and release) it promptly?

(Just replace the method body with the line:
`return InetAddress.getByName("api.openweathermap.org").isReachable(10000);`
+catching exceptions?)

**Comment by esrat** [comment]
And while you're on it, can you please include the fix for this little thing as well?:
https://github.com/SecUSo/privacy-friendly-weather/issues/79

It's really really ugly for German people. ",0" is not a number! ... I'm looking at these for days now since the app never got any data, because it thinks it has no Internet connection.

**Comment by esrat** [comment]
Um, sorry for asking here, but right now I'm really puzzled:
What does "esrat unassigned max-dreger 1 hour ago" mean???

I only commented with a possible solution and did not mention any user!?

**Comment by esrat** [comment]
Hello?
Is this a dead project already?

**Comment by esrat** [comment]
Sadly, I have to contradict!
Now we have 2020, 15 weeks after I proposed a solution for this little problem.
For everybody with a running development environment this would have been a 5-min-change! And everybody using a firewall would have been enabled to use the app.
But there was not a single change in the source code since I found this project. It is definitively dead!

**Comment by esrat** [comment]
Thank you!
What a coincident! Just some days ago I invested the time to set up a matching Android Studio to try the fix myself. I was at least capable of installing and using a debug build which worked as expected.

I will comment a little more at your fix of #79 at that place.
