### ISSUE TITLE
0,x °C is displayed without 0

### ISSUE THREAD

**Issue by kolAflash** [SecUSo/privacy-friendly-weather#79]
Inside the app, for the daily view, the 0 is missing when the temperature is 0,x or -0,x degrees.

E.g.:
0,5 -> ,5
-0,3 -> ,3

**Comment by petermayer** [comment]
Hi, thanks for reporting this. Could be easily reproduced.

**Comment by esrat** [comment]
Thanks again for working on this issue.
I've seen your class StringFormatUtils with its special case for the German language. I do think that this is neither necessary nor correct!
The JavaDoc (https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html) states that the '.'-character denotes the **already localized** "Decimal separator or monetary decimal separator". That means, a format string of "0.0" would fit all languages together in a correct manner.
I already tested this on my own and it works just fine - also for German settings.

Just a little extra:
Since you externalized the creation of the DecimalFormat-object, you would be able to store the result in a static variable so you could re-use the instance to save time and space for multiple object creation since their configuration will never differ from each other.

**Comment by Kamuno** [comment]
You are indeed correct.. Thank you :)
