### ISSUE TITLE
"Course of the day" times are bugged.

### ISSUE THREAD

**Issue by spaceoden** [SecUSo/privacy-friendly-weather#93]
I'm using version 2.2 from F-Droid. The following screenshot was taken at 12:31PM PST. The current temperature appears to be correct, but for some reason, the "Course of the day" section starts at 9:00PM, and the temperatures associated with the times are probably wrong, as they show the temperature peaking after sundown and bottoming out at noon.
![Screenshot_20200611-123154](https://user-images.githubusercontent.com/26421479/84431315-f5e98500-abdf-11ea-88b2-4b9887f383a7.png)

**Comment by MichaelMcDonnell** [comment]
Same here in Mountain View California. The course of the week is similarly broken.

**Comment by sleep-yearning** [comment]
Thanks for reporting!
This should be fixed in f34a6b0fb9b9d5497251e2715d57b86086c504f8
@MichaelMcDonnell what do you mean with course of the week, since there are no times displayed?

**Comment by MichaelMcDonnell** [comment]
> @MichaelMcDonnell what do you mean with course of the week, since there are no times displayed?

Sorry for not being clear. The course of the week is also broken. I expected it to show the high of every day, but it doesn't do that. The displayed temperatures are much lower.

I suspect the course of the week code picks some time of the day to show the temperature for instead of the high (I haven't looked at the code). It results in California looking much colder than it really is.

**Comment by sleep-yearning** [comment]
Oh okay, yes we are working on that currently.
I'll close this for now, since it's tracked on your issue.

**Comment by MichaelMcDonnell** [comment]
Awesome! Thank you @sleep-yearning!
